build "core init app/automotive"
create_boot_directory
install_config {
 <config>
  <parent-provides>
   <service name="LOG"/>
   <service name="RM"/>
  </parent-provides>
  <default-route>
   <any-service> <parent/> </any-service>
  </default-route>
  <start name="automotive">
    <resource name="RAM" quantum="100M"/>
  </start> </config>
}
build_boot_image "core init automotive"
append qemu_args "-nographic -m 64"
run_genode_until {child "automotive" exited with exit value 0} 10
